### PR TITLE
OHRI-148 Today hts client tile and list

### PR DESCRIPTION
**Pull request by pirupius**
Screenshot 2021-07-15 at 18 27 58

### CODE REVIEW

**Comment by samuelmale** [comment]
Hey @pirupius, why does this PR have all the commits? Are you sure your not having changes from working?

**Comment by samuelmale** [comment]
Be sure that UCSF-IGHS/ohri-148-today-hts-client-tile-and-list branch is rebased against dev

**Comment by pirupius** [comment]
@samuelmale i also noticed it. Will rebase the feature branch to dev to see if it resolves it.

**Comment by pirupius** [comment]
@samuelmale my branch PR to working had conflicts and during the rebase to resolve those conflicts, that's when these commits came in from the working branch. 

Should i just create another branch and cherry-pick my commits only?

**Comment by samuelmale** [comment]
> @samuelmale my branch PR to working had conflicts and during the rebase to resolve those conflicts, that's when these commits came in from the working branch.

We don't rebase our feature branches against working, you do that from your working folk. 

> Should i just create another branch and cherry-pick my commits only?

If that will help get rid of the other commits, yes.

**Pull request merged**
