### PR TITLE
(refactor) OHRI-2222 Implement the Maternal and Child Care package schema workflow

### PR DESCRIPTION
**Pull request by CynthiaKamau**
…hema workflow

## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes the ticket number in the format `OHRI-123 My PR title`.
- [ ] My work includes tests or is validated by existing tests.

## Screenshots

Before : 
Screenshot 2024-06-05 at 18 14 02
Screenshot 2024-06-05 at 18 13 52

After : 
Screenshot 2024-06-05 at 18 12 45
Screenshot 2024-06-05 at 18 12 33

### CODE REVIEW

**Review by hadijahkyampeire — COMMENTED** [review]
I have changed the pmtct to run on dev and the tables are different, I am not sure why but you probably need to check that, Also the EDD column needs to pass `isDate` true so that it formats the date, check the screenshots below.
- Your local branch
Screenshot 2024-06-06 at 13 22 23

- whats on dev
Screenshot 2024-06-06 at 13 22 39

**Comment by CynthiaKamau** [comment]
@hadijahkyampeire : https://www.loom.com/share/9c19483daf814cb495ac1fac11f89055?sid=3d340310-ca69-46ca-905d-a1c87ae25f30

**Review by hadijahkyampeire — APPROVED** [review]
Thanks @CynthiaKamau let's merge this and also update the distro.

**Comment by CynthiaKamau** [comment]
> Thanks @CynthiaKamau let's merge this and also update the distro.

https://github.com/UCSF-IGHS/openmrs-distro-referenceapplication/pull/228

**Pull request merged**
