### PR TITLE
OHRI-2259 Refactor redundant covid package api calls to commons lib

### PR DESCRIPTION
**Pull request by CynthiaKamau**
## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes the ticket number in the format `OHRI-123 My PR title`.
- [ ] My work includes tests or is validated by existing tests.

## Summary

- Removed unused files and endpoints from covid app
- Fixed workspace issue in cohort list

### CODE REVIEW

**Review by hadijahkyampeire — COMMENTED** [review]
@CynthiaKamau where did you move the fetch function `fetchPatientCovidOutcome` to? Remember it is being used in the out-comes component in the covid OR we don't need those tiles anymore?

**Comment by CynthiaKamau** [comment]
> @CynthiaKamau where did you move the fetch function `fetchPatientCovidOutcome` to? Remember it is being used in the out-comes component in the covid OR we don't need those tiles anymore?

That file that contained the endpoint is not being used anymore, strangely enough, the same endpoint was in the commons lib

**Comment by hadijahkyampeire** [comment]
But the what out the tiles you have deleted, aren't we using them anymore?

**Comment by CynthiaKamau** [comment]
> But the what out the tiles you have deleted, aren't we using them anymore?

On demo, the only tiles are for the patient counts in the `CovidSummaryTiles ` component, and on the patient chart there no tiles

**Review by hadijahkyampeire — APPROVED** [review]
Thanks @CynthiaKamau

**Pull request merged**
