### PR TITLE
OHRI-2280 Latest HIV Test Result displayed on patient banner

### PR DESCRIPTION
**Pull request by ODORA0**
## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes the ticket number in the format `OHRI-123 My PR title`.
- [ ] My work includes tests or is validated by existing tests.

## Screenshots
https://github.com/user-attachments/assets/916433bd-5d7c-4e22-a441-3a0af2de4dfe

https://github.com/user-attachments/assets/3ef200e5-88b7-4e8f-8a70-166cfb858342

## Related Issue

https://ohri.atlassian.net/browse/OHRI-2280

### CODE REVIEW

**Review by CynthiaKamau — COMMENTED** [review]
Thanks @ODORA0, is this the only tag to go to the banner or there will be others ?

**Comment by CynthiaKamau** [comment]
> @CynthiaKamau In the ticket they preferred displaying those two tags

Okay

**Review by lucyjemutai — DISMISSED** [review]
LG

**Review by hadijahkyampeire — APPROVED** [review]
Thanks @ODORA0

**Pull request merged**
