### PR TITLE
fixing build issues with npm v8

### PR DESCRIPTION
**Pull request by pirupius**

### CODE REVIEW

**Comment by samuelmale** [comment]
@pirupius Great to see someone finally looking into this; however, why does it break the tests on node '14.x'? I find that scary.

**Comment by pirupius** [comment]
@samuelmale tests are passing on local with node 14.x waiting to see if the github CI will pass as well

Screenshot 2022-02-09 at 17 37 49

**Comment by pirupius** [comment]
@samuelmale the changes are backward compatible the issue was just the CI being upgraded to node 16.x this PR can be merged.

**Comment by samuelmale** [comment]
Thanks @pirupius

**Review by samuelmale — APPROVED** [review]

**Pull request merged**
