### PR TITLE
(fix) O3-4052: Wrap SideNavMenu title in t function

### PR DESCRIPTION
**Pull request by NethmiRodrigo**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes the ticket number in the format `OHRI-123 My PR title`.
- [ ] My work includes tests or is validated by existing tests.

## Summary

When there is a grouped link the NavBarMenu title does not get translated. This PR fixes that by wrapping the title in the `t` function.

## Screenshots

After fix:
Screenshot 2024-10-03 at 11 02 49 AM

Before fix:
Screenshot 2024-10-03 at 11 04 29 AM

## Related Issue

https://ohri.atlassian.net/browse/O3-4052

## Other

I had to upgrade the openmrs framework version which is why I included the yarn.lock.

### CODE REVIEW

**Comment by NethmiRodrigo** [comment]
@ibacher @CynthiaKamau requesting for a review, can't seem to be able to do it on the UI

**Review by ibacher — APPROVED** [review]

**Review by samuelmale — APPROVED** [review]

**Review by CynthiaKamau — COMMENTED** [review]
Thanks @NethmiRodrigo , please fix the build errors

**Comment by NethmiRodrigo** [comment]
@CynthiaKamau I updated the yarn.lock again, could you please approve the workflows, thanks.

**Comment by gracepotma** [comment]
Maybe an obvious question but: Why do we need to work in here instead of in the OpenMRS repo: https://github.com/openmrs/openmrs-content-hiv

**Comment by NethmiRodrigo** [comment]
@gracepotma this PR was to make the string that shows up in the navbar translatable, so its not a part of the content but rather a fix to the implementation.

**Comment by NethmiRodrigo** [comment]
@CynthiaKamau I updated the `encounter-tile.test` to fix the importDynamic initialization error. Could you please re-run the worflows?

**Comment by NethmiRodrigo** [comment]
@CynthiaKamau `es2022` was missing in the `tsconfig` in esm-commons-lib, I added it and the build passed locally, could you please approve the workflows again?

**Comment by NethmiRodrigo** [comment]
@CynthiaKamau the e2e test was failing because the defaultLocale was set to French in the instance, I've changed it back to English and it passes locally, could you re-run the workflow?

**Review by CynthiaKamau — COMMENTED** [review]
Thanks @NethmiRodrigo

**Review by CynthiaKamau — APPROVED** [review]

**Comment by NethmiRodrigo** [comment]
Thanks for reviewing @CynthiaKamau, could you please merge this in, I don't have the permission to do so.

**Comment by CynthiaKamau** [comment]
> @CynthiaKamau I updated the `encounter-tile.test` to fix the importDynamic initialization error. Could you please re-run the worflows?

Done

**Pull request merged**
