### PR TITLE
(feat) Adding delete functionality to the encounter list component

### PR DESCRIPTION
**Pull request by arodidev**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes the ticket number in the format `OHRI-123 My PR title`.
- [ ] My work includes tests or is validated by existing tests.

## Summary

This PR introduces the ability to delete an encounter from the action items provided within each row in the `EncounterList` component, as it was deemed as a necesary feature that helps unblock workflows within Ethiohri. 

By default, the `EncounterList` will now provide a third action (delete encounter) under action items instead of the previously provided two (view encounter , edit encounter). 

Screenshot 2024-04-05 at 17 07 01

Although the action item can still be passed when calling the `EncounterList` with mode set to `delete`.

Screenshot 2024-04-05 at 10 34 12

This action makes a `DELETE` request to the encounter endpoint and takes the `encounterUuid` as a parameter. 
## Screenshots

https://github.com/UCSF-IGHS/openmrs-esm-ohri/assets/51090527/c4ec69d6-c5bc-4364-9e5f-bc064653c3b2

### CODE REVIEW

**Review by CynthiaKamau — APPROVED** [review]

**Comment by ebambo** [comment]
> @ebambo Could this be merged to unblock the Ethiopia folks as we work on the remaining bits?

@arodidev I guess that by remaining bits you mean the tests right ? Also can you make the `delete` option configurable ? You can let it be there by default but some implementation may want to hide that option to avoid mistakes.

**Comment by arodidev** [comment]
> > @ebambo Could this be merged to unblock the Ethiopia folks as we work on the remaining bits?
> 
> @arodidev I guess that by remaining bits you mean the tests right ? 

Yes, I was referring to the tests. And also, for configurability, the default action items that are available will include the `delete` option, but when you pass `actions` when calling the `EncounterList`, you can choose whether or not to pass the delete action item and it is going to override any default actions available.

**Review by CynthiaKamau — APPROVED** [review]

**Review by ODORA0 — DISMISSED** [review]

**Review by CynthiaKamau — DISMISSED** [review]
@arodidev kindly fix the conflicts

**Review by hadijahkyampeire — APPROVED** [review]
LGTM, thanks @arodidev

**Review by hadijahkyampeire — APPROVED** [review]
LGTM, thanks @arodidev

**Comment by arodidev** [comment]
> LGTM, thanks @arodidev

@hadijahkyampeire are you able to dismiss someone else's requested changes?

**Comment by hadijahkyampeire** [comment]
Yes, I can, I have just seen your question @arodidev but it looks like you got it.

**Pull request merged**
